mj:
  discord:
    guild-id: 1136680226361975036
    channel-id: 1136680226361975039
    user-token: NjMxNTQ0NjY0ODIxOTg5NDE2.GfDdnz.AtseVEkCyxiMoh-Usq7oqj7sEFn3l2_Ej2CZkY
    session-id: 2fa61761d418569e509a55fccbd22e93
    user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
  task-store:
    type: redis
    timeout: 30d
  queue:
    timeout-minutes: 5
    core-size: 3
    queue-size: 10
  translate-way: gpt
  openai:
    gpt-api-key: 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
spring:
  redis:
    host: 43.156.132.114
    #    host: 129.226.152.233
    port: 6379
    password: letsgoteam.123456
