mj:
  discord:
    guild-id: 1136680226361975036
    channel-id: 1136680226361975039
    user-token: NjMxNTQ0NjY0ODIxOTg5NDE2.GVBuJS.YNwMfwn2XhyyCm6xGuM86UZIRHCONsupcx_CQc
    session-id: cb671951461da0cf9d3fbc2d461362e6
    user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
  task-store:
    type: in_memory
    timeout: 30d
  translate-way: null
  queue:
    timeout-minutes: 5
    core-size: 3
    queue-size: 10